### ISSUE TITLE
GitCredentialManager.Trace2Exception: 'Failed to decrypt file '/home/bairog/.password-store/myapp/https/foo.com/myusr.gpg' with gpg

### ISSUE THREAD

**Issue by bairog** [devlooped/CredentialManager#108]
## Describe the Bug
I've installed WSL2 (Ubuntu 22.04.4 LTS distro) on my Windows 11 23H2 x64 Pro.
I've configured [GPG/pass compatible files](https://github.com/git-ecosystem/git-credential-manager/blob/main/docs/credstores.md#gpgpass-compatible-files) credential store for gpg-id `admin <admin@admin.com>`.
I've created .NET 6.0 console application (Visual Studio 2022) with sample code from this repository and started debugging on WSL2.
I've got an exception on credential retrieve with `Credential cred = store.Get("https://foo.com", "myusr");`:
> GitCredentialManager.Trace2Exception: 'Failed to decrypt file '/home/admin/.password-store/myapp/https/foo.com/myusr.gpg' with gpg. exit=2, out=, err=gpg: encrypted with 3072-bit RSA key, ID 9C0994D00C0203A4, created 2024-07-29
>       "admin <admin@admin.com>"
> gpg: public key decryption failed: Inappropriate ioctl for device
> gpg: decryption failed: No secret key

Is it a bug or how to fix that? Thank you.

## Steps to Reproduce

```c#
using GitCredentialManager;
using System;

namespace ConsoleApp1
{
    internal class Program
    {
        static void Main(string[] args)
        {
            ICredentialStore store = CredentialManager.Create("myapp");

            // Store a credential
            store.AddOrUpdate("https://foo.com", "myusr", "mypwd");

            // Retrieve a credential
            ICredential cred = store.Get("https://foo.com", "myusr");
        }
    }
}
```

## Expected Behavior

Credential is retreived with no problem.

## Exception with Stack Trace

```text
Exception thrown: 'GitCredentialManager.Trace2Exception' in Devlooped.CredentialManager.dll
An unhandled exception of type 'GitCredentialManager.Trace2Exception' occurred in Devlooped.CredentialManager.dll: 'Failed to decrypt file '/home/admin/.password-store/myapp/https/foo.com/myusr.gpg' with gpg. exit=2, out=, err=gpg: encrypted with 3072-bit RSA key, ID 9C0994D00C0203A4, created 2024-07-29
      "admin<admin@admin.com>"
gpg: public key decryption failed: Inappropriate ioctl for device
gpg: decryption failed: No secret key'
Stack trace:
 >   at GitCredentialManager.Gpg.DecryptFile(String path)
 >   at GitCredentialManager.Interop.Posix.GpgPassCredentialStore.TryDeserializeCredential(String path, FileCredential& credential)
 >   at GitCredentialManager.PlaintextCredentialStore.<Enumerate>d__18.MoveNext()
 >   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
 >   at GitCredentialManager.PlaintextCredentialStore.AddOrUpdate(String service, String account, String secret)
 >   at ConsoleApp1.Program.Main(String[] args) in D:\ConsoleApp1\ConsoleApp1\Program.cs:line 14
```

## Version Info

Devlooped.CredentialManager Version="2.5.0.1"

**Comment by bairog** [comment]
Code above works only if I don't enter a passphrase to protect my key (tha I generate with `gpg --gen-key`). But if I enter any passphrase - exception above is thrown. Looks like OS waits for a passphrase to be entered. Is there any workaround?

**Comment by bairog** [comment]
Ok, looks like WSL2 terminal window is treated as `Headless/TTY-only session` and therefore according to [GCM docs](https://github.com/git-ecosystem/git-credential-manager/blob/main/docs/credstores.md#headlesstty-only-sessions) I need to add `export GPG_TTY=$(tty)` to ~/.bashrc or ~/.profile file. After that a prompt started to open WSL2 terminal window (or in a GUI window if Seahorse is installed):
![image](https://github.com/user-attachments/assets/3f68ea51-aa5d-49d7-a22b-565582dbd30f)
If GPG key passphrase is not empty `[GPG/pass compatible files](https://github.com/git-ecosystem/git-credential-manager/blob/main/docs/credstores.md#gpgpass-compatible-files)` credential store also requires user interaction (via GUI or terminal prompt)? Is there any workaround to enter a passphrase via API?

**Comment by bairog** [comment]
@kzu "to work on non-interactive usage" - do you mean gpg key without any passphrase is the only option? [Secret Service API](https://github.com/git-ecosystem/git-credential-manager/blob/main/docs/credstores.md#freedesktoporg-secret-service-api) definitelly require GUI, [credential cache](https://github.com/git-ecosystem/git-credential-manager/blob/main/docs/credstores.md#gits-built-in-credential-cachee) is not persistent, [Plaintext files](https://github.com/git-ecosystem/git-credential-manager/blob/main/docs/credstores.md#plaintext-files) are not secure at all. So [GPG/pass compatible files](https://github.com/git-ecosystem/git-credential-manager/blob/main/docs/credstores.md#gpgpass-compatible-files) is the only non-interactive store available on Linux, right?

**Comment by kzu** [comment]
I guess. But as I said, that's all external to this library.
