### ISSUE TITLE
Bump to GCM v2.6.0

### ISSUE THREAD

**Issue by xtqqczze** [devlooped/CredentialManager#109]
See https://github.com/git-ecosystem/git-credential-manager/releases/tag/v2.6.0

[![Back this issue](https://raw.githubusercontent.com/devlooped/SponsorLink/main/docs/assets/img/separator.png "Back this issue")](https://www.devlooped.com/SponsorLink/github/issues/?s=devlooped)
[![Back this issue](https://img.shields.io/badge/backed-%240-EA4AAA?logo=githubsponsors "Back this issue")](https://www.devlooped.com/SponsorLink/github/issues/?s=devlooped)

**Comment by kzu** [comment]
Fixed in https://github.com/devlooped/CredentialManager/pull/111
